port: 8080
root: "{{VIRTUAL_ENV}}/piccl.clam"
piccldir: "{{VIRTUAL_ENV}}/opt/PICCL"
piccldataroot: "{{VIRTUAL_ENV}}/opt/PICCL"
autosearch_forward_url: "https://portal.clarin.inl.nl/autocorp/upload/?format=piccl&file=$BACKLINK"
